INFO  2023-08-22 14:58:37,409 minitest.py init_miniprogram 144 start init miniprogram
INFO  2023-08-22 14:58:37,417 basenative.py wrapper         24  call IdeNative.start_wechat
INFO  2023-08-22 14:58:37,418 basenative.py wrapper         28  call IdeNative.start_wechat end
INFO  2023-08-22 14:58:37,420 minium_object.py _do_shell       83  de shell: where cli.bat
INFO  2023-08-22 14:58:37,606 minium_object.py _do_shell       101 err:
信息: 用提供的模式无法找到文件。

INFO  2023-08-22 14:58:37,606 minium_object.py _do_shell       102 out:

WARNI 2023-08-22 14:58:37,607 wx_minium.py __setup_dev_tool 190 default dev_tool_path[C:/Program Files (x86)/Tencent/微信web开发者工具/cli.bat] not exists and command[cli.bat] not found
INFO  2023-08-22 14:58:37,607 wx_minium.py launch_dev_tool 565 Starting dev tool and launch MiniProgram project ...
WARNI 2023-08-22 14:58:37,608 wx_minium.py launch_dev_tool 610 Can not find `project_path` in config, that means you must open dev tool by automation way first
WARNI 2023-08-22 14:58:37,608 wx_minium.py launch_dev_tool 614 If you are not running command like [cli auto --project /path/to/project --auto-port 9420], you may config `project_path` or run this command first
INFO  2023-08-22 14:58:37,609 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 14:58:41,804 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 14:58:41,881 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 14:58:41,974 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 14:58:42,018 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 14:58:46,261 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 14:58:46,322 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 14:58:46,430 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 14:58:46,433 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
INFO  2023-08-22 14:58:49,250 minitest.py init_miniprogram 144 start init miniprogram
INFO  2023-08-22 14:58:49,253 basenative.py wrapper         24  call IdeNative.start_wechat
INFO  2023-08-22 14:58:49,292 basenative.py wrapper         28  call IdeNative.start_wechat end
INFO  2023-08-22 14:58:49,294 minium_object.py _do_shell       83  de shell: where cli.bat
INFO  2023-08-22 14:58:49,465 minium_object.py _do_shell       101 err:
信息: 用提供的模式无法找到文件。

INFO  2023-08-22 14:58:49,466 minium_object.py _do_shell       102 out:

WARNI 2023-08-22 14:58:49,466 wx_minium.py __setup_dev_tool 190 default dev_tool_path[C:/Program Files (x86)/Tencent/微信web开发者工具/cli.bat] not exists and command[cli.bat] not found
INFO  2023-08-22 14:58:49,467 wx_minium.py launch_dev_tool 565 Starting dev tool and launch MiniProgram project ...
WARNI 2023-08-22 14:58:49,468 wx_minium.py launch_dev_tool 610 Can not find `project_path` in config, that means you must open dev tool by automation way first
WARNI 2023-08-22 14:58:49,468 wx_minium.py launch_dev_tool 614 If you are not running command like [cli auto --project /path/to/project --auto-port 9420], you may config `project_path` or run this command first
INFO  2023-08-22 14:58:49,468 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 14:58:50,655 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 14:58:50,748 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 14:58:50,856 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
ERROR 2023-08-22 14:58:50,857 wx_minium.py launch_dev_tool 624 three times try to connect Dev tool has all fail ..., restart now...
ERROR 2023-08-22 14:58:53,698 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 14:58:53,841 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 14:58:53,949 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 14:58:53,954 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 14:58:58,156 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 14:58:58,203 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 14:58:58,251 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 14:58:58,252 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 14:59:02,490 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 14:59:02,598 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 14:59:02,690 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
ERROR 2023-08-22 14:59:02,691 wx_minium.py launch_dev_tool 624 three times try to connect Dev tool has all fail ..., restart now...
INFO  2023-08-22 15:04:30,989 minitest.py init_miniprogram 144 start init miniprogram
INFO  2023-08-22 15:04:30,993 basenative.py wrapper         24  call IdeNative.start_wechat
INFO  2023-08-22 15:04:30,994 basenative.py wrapper         28  call IdeNative.start_wechat end
INFO  2023-08-22 15:04:30,997 minium_object.py _do_shell       83  de shell: where cli.bat
INFO  2023-08-22 15:04:31,136 minium_object.py _do_shell       101 err:
信息: 用提供的模式无法找到文件。

INFO  2023-08-22 15:04:31,136 minium_object.py _do_shell       102 out:

WARNI 2023-08-22 15:04:31,136 wx_minium.py __setup_dev_tool 190 default dev_tool_path[C:/Program Files (x86)/Tencent/微信web开发者工具/cli.bat] not exists and command[cli.bat] not found
INFO  2023-08-22 15:04:31,136 wx_minium.py launch_dev_tool 565 Starting dev tool and launch MiniProgram project ...
WARNI 2023-08-22 15:04:31,137 wx_minium.py launch_dev_tool 610 Can not find `project_path` in config, that means you must open dev tool by automation way first
WARNI 2023-08-22 15:04:31,137 wx_minium.py launch_dev_tool 614 If you are not running command like [cli auto --project /path/to/project --auto-port 9420], you may config `project_path` or run this command first
INFO  2023-08-22 15:04:31,138 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 15:04:35,395 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:04:35,441 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 15:04:35,519 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:04:35,527 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 15:04:39,746 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:04:39,824 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 15:04:39,917 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:04:39,919 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 15:04:44,133 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:04:44,225 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 15:04:44,289 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
ERROR 2023-08-22 15:04:44,291 wx_minium.py launch_dev_tool 624 three times try to connect Dev tool has all fail ..., restart now...
INFO  2023-08-22 15:13:55,728 minitest.py init_miniprogram 144 start init miniprogram
INFO  2023-08-22 15:13:55,731 basenative.py wrapper         24  call IdeNative.start_wechat
INFO  2023-08-22 15:13:55,732 basenative.py wrapper         28  call IdeNative.start_wechat end
INFO  2023-08-22 15:13:55,733 minium_object.py _do_shell       83  de shell: where cli.bat
INFO  2023-08-22 15:13:55,863 minium_object.py _do_shell       101 err:
信息: 用提供的模式无法找到文件。

INFO  2023-08-22 15:13:55,863 minium_object.py _do_shell       102 out:

WARNI 2023-08-22 15:13:55,864 wx_minium.py __setup_dev_tool 190 default dev_tool_path[C:/Program Files (x86)/Tencent/微信web开发者工具/cli.bat] not exists and command[cli.bat] not found
INFO  2023-08-22 15:13:55,864 wx_minium.py launch_dev_tool 565 Starting dev tool and launch MiniProgram project ...
WARNI 2023-08-22 15:13:55,865 wx_minium.py launch_dev_tool 610 Can not find `project_path` in config, that means you must open dev tool by automation way first
WARNI 2023-08-22 15:13:55,865 wx_minium.py launch_dev_tool 614 If you are not running command like [cli auto --project /path/to/project --auto-port 9420], you may config `project_path` or run this command first
INFO  2023-08-22 15:13:55,865 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 15:14:00,144 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:14:00,252 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 15:14:00,331 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:14:00,337 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 15:14:04,591 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:14:04,668 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 15:14:04,762 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:14:04,763 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 15:14:09,043 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:14:09,069 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 15:14:09,072 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
ERROR 2023-08-22 15:14:09,079 wx_minium.py launch_dev_tool 624 three times try to connect Dev tool has all fail ..., restart now...
INFO  2023-08-22 15:32:53,075 minitest.py init_miniprogram 144 start init miniprogram
INFO  2023-08-22 15:32:53,077 basenative.py wrapper         24  call IdeNative.start_wechat
INFO  2023-08-22 15:32:53,078 basenative.py wrapper         28  call IdeNative.start_wechat end
INFO  2023-08-22 15:32:53,079 minium_object.py _do_shell       83  de shell: where cli.bat
INFO  2023-08-22 15:32:53,227 minium_object.py _do_shell       101 err:
信息: 用提供的模式无法找到文件。

INFO  2023-08-22 15:32:53,227 minium_object.py _do_shell       102 out:

WARNI 2023-08-22 15:32:53,228 wx_minium.py __setup_dev_tool 190 default dev_tool_path[C:/Program Files (x86)/Tencent/微信web开发者工具/cli.bat] not exists and command[cli.bat] not found
INFO  2023-08-22 15:32:53,228 wx_minium.py launch_dev_tool 565 Starting dev tool and launch MiniProgram project ...
WARNI 2023-08-22 15:32:53,228 wx_minium.py launch_dev_tool 610 Can not find `project_path` in config, that means you must open dev tool by automation way first
WARNI 2023-08-22 15:32:53,228 wx_minium.py launch_dev_tool 614 If you are not running command like [cli auto --project /path/to/project --auto-port 9420], you may config `project_path` or run this command first
INFO  2023-08-22 15:32:53,229 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 15:32:57,427 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:32:57,488 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 15:32:57,581 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:32:57,587 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 15:33:01,762 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:33:01,824 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 15:33:01,886 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:33:01,886 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-08-22 15:33:06,118 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-08-22 15:33:06,148 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-08-22 15:33:06,225 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
ERROR 2023-08-22 15:33:06,226 wx_minium.py launch_dev_tool 624 three times try to connect Dev tool has all fail ..., restart now...
