INFO  2023-09-05 14:06:12,831 minitest.py init_miniprogram 144 start init miniprogram
INFO  2023-09-05 14:06:12,839 basenative.py wrapper         24  call IdeNative.start_wechat
INFO  2023-09-05 14:06:12,841 basenative.py wrapper         28  call IdeNative.start_wechat end
INFO  2023-09-05 14:06:12,843 minium_object.py _do_shell       83  de shell: where cli.bat
INFO  2023-09-05 14:06:13,001 minium_object.py _do_shell       101 err:
信息: 用提供的模式无法找到文件。

INFO  2023-09-05 14:06:13,002 minium_object.py _do_shell       102 out:

WARNI 2023-09-05 14:06:13,002 wx_minium.py __setup_dev_tool 190 default dev_tool_path[C:/Program Files (x86)/Tencent/微信web开发者工具/cli.bat] not exists and command[cli.bat] not found
INFO  2023-09-05 14:06:13,003 wx_minium.py launch_dev_tool 565 Starting dev tool and launch MiniProgram project ...
WARNI 2023-09-05 14:06:13,003 wx_minium.py launch_dev_tool 610 Can not find `project_path` in config, that means you must open dev tool by automation way first
WARNI 2023-09-05 14:06:13,004 wx_minium.py launch_dev_tool 614 If you are not running command like [cli auto --project /path/to/project --auto-port 9420], you may config `project_path` or run this command first
INFO  2023-09-05 14:06:13,004 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-09-05 14:06:17,238 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-09-05 14:06:17,317 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-09-05 14:06:17,410 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-09-05 14:06:17,444 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-09-05 14:06:21,630 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-09-05 14:06:21,708 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-09-05 14:06:21,803 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-09-05 14:06:21,806 wx_minium.py connect_dev_tool 661 Trying to connect Dev tool ...
ERROR 2023-09-05 14:06:26,046 connection.py _on_error       632 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
INFO  2023-09-05 14:06:26,123 connection.py _ws_run_forever 367 websocket run forever shutdown
ERROR 2023-09-05 14:06:26,201 wx_minium.py connect_dev_tool 681 [WinError 10061] 由于目标计算机积极拒绝，无法连接。
Traceback (most recent call last):
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\wx_minium.py", line 662, in connect_dev_tool
    self.connection = Connection.create(
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 169, in create
    instance = cls(uri, *args, **kwargs)
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 209, in __init__
    self._connect()
  File "D:\software\python-3.10.10\lib\site-packages\minium\miniprogram\base_driver\connection.py", line 351, in _connect
    raise error_callback.result
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_app.py", line 327, in run_forever
    self.sock.connect(
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_core.py", line 244, in connect
    self.sock, addrs = connect(url, self.sock_opt, proxy_info(**options),
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 130, in connect
    sock = _open_socket(addrinfo_list, options.sockopt, options.timeout)
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 205, in _open_socket
    raise err
  File "D:\software\python-3.10.10\lib\site-packages\websocket\_http.py", line 185, in _open_socket
    sock.connect(address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
ERROR 2023-09-05 14:06:26,203 wx_minium.py launch_dev_tool 624 three times try to connect Dev tool has all fail ..., restart now...
